apiVersion: v1
kind: Template 
metadata:
  name: template-db1
objects: 
- apiVersion: v1
  kind: Pod
  metadata:
    name: app1
  spec:
    containers:
    - env:
      - name: MYSQL_ROOT_PASSWORD
        value: ${MYSQL_ROOT_PASSWORD} 
      image: centos/mariadb-101-centos7:latest
      name: db1
      ports: 
      - containerPort: 3306
        protocol: TCP
parameters: 
- description: My db
  name: MYSQL_ROOT_PASSWORD
  required: true
labels:
  mylabel: app1
